version: '3.9'

services:
    api:
        container_name: nest_cute_api
        restart: always
        image: node:17.7-alpine
        volumes:
            - .:/app:rw
        working_dir: /app
        command: npm run start:dev
        env_file:
            - .env
        ports:
            - '${PORT}:${PORT}'
        logging:
            driver: 'json-file'
            options:
                max-file: '1'
                max-size: '5m'
