name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Create SHA Container Tag
        id: sha_tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "::set-output name=tag::$tag"
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/r-priyam/nestjs-boilerplate:latest
          cache-to: type=inline
          tags: |
            ghcr.io/r-priyam/nestjs-boilerplate:latest
            ghcr.io/r-priyam/nestjs-boilerplate:${{ steps.sha_tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}